
---
错误处理
---

# 1 基础error

## 1.1 error接口
error是一种内建的接口类型，内建意味着不需要import任何包就可以直接使用，使用起来就像int、string一样自然。

```golang
type error interface {
    Error() string
}
```

error接口只声明了一个Error()方法，任何实现了该方法的结构体都可以作为error来使用。error的实例代表一种异常状态，
Error()方法用于描述该异常状态，值为nil的error代表没有异常。

标准库errors包中的errorString就是实现error接口的一个例子：

```golang
type errorString struct {
    s string
}

func (e *errorString) Error() string {
    return e.s
}
```

errorString是errors包的私有类型，对外不可见，只能通过对应的公开接口才可以创建errorString实例。

## 1.2 创建error

标准库提供了两种创建error的方法:
errors.New()
fmt.Errorf()


> errors.New()

errors.New()的实现极其简单，只是简单地构造一个errorString实例便返回：
```golang
func New(text string) error {
	return &errorString{text}
}
```

> fmt.Errorf()

errors.New()单调地接收一个字符串参数来构造error，而实际场景中往往需要使用fmt.Sprintf()生成字符串，这时可以直接使用fmt.Errorf()

```golang
package fmt

func Errorf(format string, a ...interface{}) error {
    return errors.New(Sprintf(format, a...))
} 
```

可以看到，fmt.Errorf()只是针对 errors.New()的简单封装，使用fmt.Errorf()可以使代码更简洁:

```golang
errStr := fmt.Sprintf("file not found, file name: %s", fileName)
err := errors.New(errStr)

//或
err := errors.New(fmt.Sprintf("file not found, file name: %", fileName))

// 可以替换为:

err := fmt.Errorf("file not found, file name: %s", fileName)
```

总体而言，fmt.Errorf()适用于需要格式化输出错误字符串的场景，如果不需要格式化字符串，则建议直接使用errors.New().


## 1.3 自定义error

任何实现error接口的类型都可以称为error。比如标准库os中的PathError就是一个典型例子：

```golang
// PathError records an error and the operation and file path that caused it.
type PathError struct {
	Op   string
	Path string
	Err  error
}

func (e *PathError) Error() string { return e.Op + " " + e.Path + ": " + e.Err.Error() }
```

> 异常处理

针对error而言，异常处理包括如何检查错误、如何传递错误。

> 检查error

最常见的检查error的方式是与nil值进行比较：

```golang
if err != nil {
    // something went wrong
}
```

有时也会与一些预定义的error进行比较:

```golang
// 标准库os包中定义了一些常见的错误
ErrPermission = errors.New("permission denied")

if err == os.ErrPermission {
    // permission denied 
}
```

由于任何实现了error接口的类型均可以作为error来处理，所以往往也会使用类型断言来检查error:

```golang

func AssertError (err error) {
    if e, ok := err.(*os.PathError); ok {
        fmt.Printf("it`s an os.PathError, operation: %s, path: %s, msg: %v", e.Op, e.Path, e.Err)
    }
}
```

上面代码中的断言，如果err是os.PathError类型，则可以使用e来访问os.PathError中的成员。


> 传递error

在一个函数中收到一个error，往往需要附加一些上下文信息再把error继续向上层抛。
最常见的添加附加上下文信息的方法是使用fmt.Errorf():

```golang
if err != nil {
    return fmt.Errorf("decompress %v: %v", name, err)
}
```

这种方式抛出的error有一个糟糕的问题，那就是原error信息和附加的信息被糅合到一起了。比如下面的函数，就会把
os.ErrPermission 和附加信息糅合到一起:

```golang
func WriteFile(fileName string) error {
    if fileName == "a.txt" {
        return fmt.Errorf("write file error: %v", os.ErrPermisssion)
    }

    return nil
}
```

为了解决这个问题，我们可以自定义error类型，就像os.PathError那样，上下文信息与原error信息分开存放:

```golang
type PathError struct {
	Op   string    // 上下文
	Path string   // 上下文
	Err  error   //  原error
}

```

这样，对于一个os.PathError类型的error, 我们可以检测它到底是不是一个权限不足的错误:

```golang
if e, ok := err.(*os.PathError); ok && e.Err == os.ErrPermisssion {
    fmt.Println("permission denied")
}
```

在上面的例子中，使用fmt.Errorf()传递一个error最大的问题是丢弃了原error值，而使用自定义error又会有不得不使用
断言的烦恼。
Go 1.13很好地解决了上面的问题和烦恼，它提供了一个错误链传递和检查机制。


# 2 链式error

在Go 1.13以前，使用fmt.Errorf()传递捕获的error并为error增加上下文信息时，原error将和上下文信息混杂在一起，
这样便无法获取原始的error。为此Go 1.13引入了一套解决方案，本节称其为链式error，因为error在函数间传递时，上下文
信息好像链条一样把各个error连接起来。

Go 1.13中针对error的优化，主要有:
> 新的error类型 wrapError；
> 增强了fmt.Errorf()以便通过%w创建wrapError；
> 引入了errors.Unwrap()以便拆解wrapError；
> 引入了errors.Is()用于检查error链条中是否包含指定的错误值；
> 引入了errors.As()用于检查error链条中是否包含指定的错误类型。

## 2.1 wrapError

```golang
type wrapError struct {
	msg string
	err error
}

func (e *wrapError) Error() string {
	return e.msg
}

func (e *wrapError) Unwrap() error {
	return e.err
}
```

wrapError初看起来很像前面介绍的os.PathError，os.PathError通过os.PathError.Op和os.PathError.Path保存上下文信息，
而wrapError的msg成员则把原error和上下文保存到一起，通过err成员保存原始的error。

此处的wrapError与之前的errorString相比，还额外实现了Unwrap()接口，用于返回原始的error。

## 2.2 fmt.Errorf()

在Go 1.13中，fmt.Errorf()新增了格式动词%w(wrap)用于生成wrapError示例，并且兼容原有格式动词。其实现源码如下:

```golang

func Errorf(format string, a ...any) error {
	p := newPrinter()
	p.wrapErrs = true
    // 解析格式，如果发现%w动词并且提供了合法的error参数，则把error放到p.wrappedErr成员中
	p.doPrintf(format, a)
	s := string(p.buf)
	var err error
    // 没有%w动词, 生成基础error
	if p.wrappedErr == nil {
		err = errors.New(s)
	} else {
        // 有%w动词, 生成wrapError
		err = &wrapError{s, p.wrappedErr}
	}
	p.free()
	return err
}
```

fmt.Errorf()将根据格式动词来动态决定生成wrapError还是errorString。使用%v格式动词生成的error类型仍是errorString,
(没有实现Unwrap接口)。

而使用%w格式动词生成的error类型将自动变成wrapError(实现了Unwrap接口)。

如此，当error在函数间传递时，error之间好像被组织成一个链式结构，如下图所示:





![chain-error.png](images%2Fchain-error.png)





使用fmt.Errorf()生成wrapError有两个限制:
每次生成wrapError时只能使用一次%w动词；
%w动词只能匹配实现了error接口的参数。

```golang
permissionErr := errors.New("permission not allowed")
wrapErr := fmt.Errorf("some context: %w", permissionErr)
```

另外需要注意的是，虽然wrapError实现了Unwrap()接口，但由于error接口仍然只定义了一个Error()方法，所以使用
fmt.Errorf()生成的error，不能直接调用自身的Unwrap()接口获得原始error，而需要使用errors包中提供的Unwrap()
方法。


## 2.3 errors.Unwrap()

Unwrap()函数很形象地揭示了其作用，如果把error比作一件衣服，fmt.Errorf() (使用%w)就好比给error增加了一件外套，
而Unwrap()函数则是脱掉外套。

```golang
func Unwrap(err error) error {
    // 检查是否实现了Unwrap函数
	u, ok := err.(interface {
		Unwrap() error
	})
    // 没有实现Unwrap函数，不支持Unwrap
	if !ok {
		return nil
	}
	return u.Unwrap()
}
```

如果参数err没有实现Unwrap()函数，则说明是基础error，直接返回nil，否则调用原err实现的Unwrap()函数并返回。

对于自定义的error类型，在实现Error()函数的基础上，需要额外实现Unwrap函数，可以升级成链式error，如os.PathError

```golang
type PathError struct {
	Op   string
	Path string
	Err  error
}

func (e *PathError) Error() string { return e.Op + " " + e.Path + ": " + e.Err.Error() }

func (e *PathError) Unwrap() error { return e.Err }
```

使用Unwrap获取原始error并进行比较的例子如下:

```golang
func ExampleUnwrap() {
    err := fmt.Errorf("write file error:%w", os.ErrPermission)
    if errors.Unwrap(err) == os.ErrPermission {
        fmt.Println("permission denied")
    }
    // Output:
    // permission denied
}
```

在上面的例子中原始的error(os.ErrPermission)只被包裹了一层，我们可以使用Unwrap()函数获取原始的error。在实际的
应用中，原始的error可能在层层的函数调用中被包裹了多层，那该怎么判断呢？

对此，我们可以循环调用Unwrap()函数来逐层检查，但是这样太过繁琐，errors包的Is()方法对此提供了更好的支持。


## 2.4 errors.Is()

errors.Is()用于检查特定的error链条中是否包含指定的error值(target)。
其实现逻辑是: errors.Is()逐层拆解参数err并与参数target对比，如果发现相等则返回true，否则返回false。对于自定义
error类型来说，如果实现了自己的Is()方法，则此处在比较时会先调用自身的Is()方法。


```golang
func ExampleIs() {
    err1 := fmt.Errorf("write file error:%w", os.ErrPermission)
    err2 := fmt.Errorf("write file error:%w", err1)
    if errors.Is(err2, os.ErrPermission)  {
        fmt.Println("permission denied")
    }
    // Output:
    // permission denied
}
```

## 2.5 errors.As()

errors.As() 用于从一个error链中查找是否有指定的类型出现，如有，则把error转换成该类型。
其实现逻辑与Is()的实现非常类似，As()会逐层拆解error链并尝试匹配指定类型，如果类型匹配，则将err值写入参数
target。同时，如果error实现了As()函数，那么也会尝试调用自身的As()函数。

## 2.6 工程迁移

细心的读者也许会发现，几乎每个版本的Release Notes中都有一句话:
"We expect almost all Go programs to continue to compile and run as before"。

Go语言的每个版本都严格遵循兼容性规则，在Go 1时代，每个小版本发布都会兼容旧版本的程序。对于Go 1.13引入的error
优化来讲也不例外，使用老版本Go语言开发的程序(下称旧工程)，仍然可以编译并运行，并且行为依旧。如果想要链式error，
那么仍需要对旧工程做一些适当的适配。

适配无非从以下几个场景入手:
> 创建error时，fmt.Errorf()格式化动词由%v改为%w；
> 等值(==)检查可以使用errors.Is()替代；
> error类型断言可以使用errors.As()替代(注意:类型断言替换成errors.As()时需要先声明一个目标类型的指针变量)；
> 自定义类型额外实现Unwrap()方法；
> 自定义类型额外实现As()方法(可选)；
> 自定义类型额外实现Is()方法(可选)；

在实际场景中，几乎不需要实现As()和Is()这两个接口，我们可以根据自身需要决定是否需要实现。